wandb_version: 1

batch_size:
  value: 32
d_model:
  value: 552
learning_rate:
  value: 0.06748568641868165
num_heads:
  value: 8
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
