wandb_version: 1

batch_size:
  value: 64
d_model:
  value: 776
learning_rate:
  value: 0.06893955557157629
num_heads:
  value: 4
num_layers:
  value: 64
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
