wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1288
learning_rate:
  value: 0.09965672794131988
num_heads:
  value: 4
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
