wandb_version: 1

batch_size:
  value: 40
d_model:
  value: 704
learning_rate:
  value: 0.03516381481715982
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
