wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1240
learning_rate:
  value: 0.092948564494078
num_heads:
  value: 16
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
