wandb_version: 1

batch_size:
  value: 96
d_model:
  value: 832
learning_rate:
  value: 0.04644242464464752
num_heads:
  value: 16
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
