wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1678305677.466202
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.13.5
      8:
      - 5
optimizer:
  desc: null
  value: adam
weight_action:
  desc: null
  value: 6.936271133116962
weight_activity:
  desc: null
  value: 2.022274903939573
weight_phrase:
  desc: null
  value: 6.7656893872503225
