wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1520
learning_rate:
  value: 0.05153824382844231
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
