wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 784
learning_rate:
  value: 0.015970731582455735
num_heads:
  value: 16
num_layers:
  value: 64
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
