wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1678165614.565654
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.13.5
      8:
      - 5
d_model:
  desc: null
  value: 712
learning_rate:
  desc: null
  value: 0.1127111248951318
num_heads:
  desc: null
  value: 4
num_layers:
  desc: null
  value: 2
optimizer:
  desc: null
  value: sgd
tag_emb_dropout:
  desc: null
  value: 0.3
weight_activity:
  desc: null
  value: 6.82599331595036
weight_phrase:
  desc: null
  value: 7.641148662430688
