wandb_version: 1

batch_size:
  value: 64
d_model:
  value: 800
learning_rate:
  value: 0.36344483522655735
num_heads:
  value: 16
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 1.4101688585910377
weight_phrase:
  value: 6.373463697195295
