wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1104
learning_rate:
  value: 0.5099952365721027
num_heads:
  value: 8
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 2.9283176789510157
weight_phrase:
  value: 1.100865295626261
