wandb_version: 1

batch_size:
  value: 40
d_model:
  value: 792
learning_rate:
  value: 0.7909899363938486
num_heads:
  value: 8
num_layers:
  value: 32
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 3.308780636560585
weight_phrase:
  value: 3.5854856775115653
