wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 616
learning_rate:
  value: 0.6226616041422429
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 5.987457786184997
weight_phrase:
  value: 5.329632883265979
