wandb_version: 1

batch_size:
  value: 112
d_model:
  value: 1560
learning_rate:
  value: 0.06935140763922952
num_heads:
  value: 8
num_layers:
  value: 4
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
