wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 512
learning_rate:
  value: 0.08809250957198568
num_heads:
  value: 16
num_layers:
  value: 4
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
