wandb_version: 1

batch_size:
  value: 80
d_model:
  value: 640
learning_rate:
  value: 0.07962871172108517
num_heads:
  value: 16
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
