wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 1304
learning_rate:
  value: 0.014024294382449063
num_heads:
  value: 4
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
