wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 568
learning_rate:
  value: 0.011396961378543149
num_heads:
  value: 16
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
