wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1872
learning_rate:
  value: 0.06486048157782993
num_heads:
  value: 8
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
