wandb_version: 1

batch_size:
  value: 48
d_model:
  value: 2008
learning_rate:
  value: 0.06660652610937777
num_heads:
  value: 4
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
