wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1667690358.263335
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.7.13
      5: 0.13.5
      8:
      - 5
batch_size:
  desc: null
  value: 8
d_model:
  desc: null
  value: 1240
learning_rate:
  desc: null
  value: 0.092948564494078
num_heads:
  desc: null
  value: 16
num_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: sgd
tag_emb_dropout:
  desc: null
  value: 0.2
