wandb_version: 1

batch_size:
  value: 104
d_model:
  value: 544
learning_rate:
  value: 0.054730020372099834
num_heads:
  value: 16
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
