wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 888
learning_rate:
  value: 0.05036471979752111
num_heads:
  value: 16
num_layers:
  value: 64
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
