wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 824
learning_rate:
  value: 0.05276605113253888
num_heads:
  value: 4
num_layers:
  value: 64
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
