wandb_version: 1

batch_size:
  value: 48
d_model:
  value: 920
learning_rate:
  value: 0.0005915078992591583
num_heads:
  value: 16
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
