wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 512
learning_rate:
  value: 0.06540241787870861
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
