wandb_version: 1

batch_size:
  value: 120
d_model:
  value: 1040
learning_rate:
  value: 0.09347998620507895
num_heads:
  value: 8
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
