wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 1600
learning_rate:
  value: 0.025865244691365464
num_heads:
  value: 4
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
