wandb_version: 1

batch_size:
  value: 64
d_model:
  value: 936
learning_rate:
  value: 0.01396209196054742
num_heads:
  value: 16
num_layers:
  value: 32
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
