wandb_version: 1

batch_size:
  value: 96
d_model:
  value: 560
learning_rate:
  value: 0.040457635235185155
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
