wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 1160
learning_rate:
  value: 0.007181422642442714
num_heads:
  value: 16
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
