wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 1184
learning_rate:
  value: 0.0780697064518597
num_heads:
  value: 16
num_layers:
  value: 32
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
