wandb_version: 1

batch_size:
  value: 32
d_model:
  value: 1120
learning_rate:
  value: 0.09214648795420433
num_heads:
  value: 4
num_layers:
  value: 4
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
