wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 2032
learning_rate:
  value: 0.0003321593825134084
num_heads:
  value: 8
num_layers:
  value: 64
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
