wandb_version: 1

batch_size:
  value: 48
d_model:
  value: 528
learning_rate:
  value: 0.06629372040072445
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
