wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 784
learning_rate:
  value: 0.09524992303350864
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
