wandb_version: 1

batch_size:
  value: 32
d_model:
  value: 1376
learning_rate:
  value: 0.0456432992823844
num_heads:
  value: 4
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
