wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 552
learning_rate:
  value: 0.0054830538861474825
num_heads:
  value: 16
num_layers:
  value: 64
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
