wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 608
learning_rate:
  value: 0.0970173325539215
num_heads:
  value: 4
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
