wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 624
learning_rate:
  value: 0.08894426579476643
num_heads:
  value: 8
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
