wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 568
learning_rate:
  value: 0.05875489285729542
num_heads:
  value: 8
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
