wandb_version: 1

batch_size:
  value: 64
d_model:
  value: 1232
learning_rate:
  value: 0.08639870909251161
num_heads:
  value: 16
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
