wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 1392
learning_rate:
  value: 0.0990113439808584
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
