wandb_version: 1

batch_size:
  value: 64
d_model:
  value: 1024
learning_rate:
  value: 0.09696012636016216
num_heads:
  value: 16
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
