wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 712
learning_rate:
  value: 0.04016577403027706
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
