wandb_version: 1

batch_size:
  value: 72
d_model:
  value: 1064
learning_rate:
  value: 0.07286269470053962
num_heads:
  value: 4
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
