wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 960
learning_rate:
  value: 0.004240045846751972
num_heads:
  value: 16
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
