wandb_version: 1

batch_size:
  value: 112
d_model:
  value: 600
learning_rate:
  value: 0.01714670103914866
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
