wandb_version: 1

batch_size:
  value: 120
d_model:
  value: 536
learning_rate:
  value: 0.08264486310011832
num_heads:
  value: 16
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
