wandb_version: 1

batch_size:
  value: 112
d_model:
  value: 720
learning_rate:
  value: 0.07374799649961282
num_heads:
  value: 8
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
