wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 1264
learning_rate:
  value: 0.0889047532372102
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
