wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 1632
learning_rate:
  value: 0.04306027046917719
num_heads:
  value: 8
num_layers:
  value: 32
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
