wandb_version: 1

batch_size:
  value: 56
d_model:
  value: 712
learning_rate:
  value: 0.0017948850783636395
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
