wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1008
learning_rate:
  value: 0.05422320194493227
num_heads:
  value: 4
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
