wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 672
learning_rate:
  value: 0.010689895173136331
num_heads:
  value: 16
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
