wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 568
learning_rate:
  value: 0.06978348943674388
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
