wandb_version: 1

batch_size:
  value: 104
d_model:
  value: 1600
learning_rate:
  value: 0.06810110515617009
num_heads:
  value: 4
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
