wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 584
learning_rate:
  value: 0.08022894734299664
num_heads:
  value: 4
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
