wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1512
learning_rate:
  value: 0.0535805589442902
num_heads:
  value: 16
num_layers:
  value: 32
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
