wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 680
learning_rate:
  value: 0.06136482319976144
num_heads:
  value: 16
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
