wandb_version: 1

batch_size:
  value: 64
d_model:
  value: 520
learning_rate:
  value: 0.021623028091430564
num_heads:
  value: 8
num_layers:
  value: 32
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
