wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1016
learning_rate:
  value: 0.08861764302519141
num_heads:
  value: 4
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
