wandb_version: 1

batch_size:
  value: 56
d_model:
  value: 1640
learning_rate:
  value: 0.0017368265680287377
num_heads:
  value: 4
num_layers:
  value: 32
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
