wandb_version: 1

batch_size:
  value: 32
d_model:
  value: 608
learning_rate:
  value: 0.08279927981684826
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
