wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 584
learning_rate:
  value: 0.04654761319860057
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
