wandb_version: 1

batch_size:
  value: 56
d_model:
  value: 1520
learning_rate:
  value: 0.07053714192102144
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
