wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 896
learning_rate:
  value: 0.08630617961392542
num_heads:
  value: 8
num_layers:
  value: 64
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
