wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 704
learning_rate:
  value: 0.0240554811676038
num_heads:
  value: 16
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
