wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1064
learning_rate:
  value: 0.01973042194913979
num_heads:
  value: 4
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
