wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 816
learning_rate:
  value: 0.08432830294177844
num_heads:
  value: 4
num_layers:
  value: 32
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
