wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 904
learning_rate:
  value: 0.03176359037752703
num_heads:
  value: 4
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
