wandb_version: 1

batch_size:
  value: 32
d_model:
  value: 880
learning_rate:
  value: 0.006289483972609922
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
