wandb_version: 1

batch_size:
  value: 56
d_model:
  value: 1648
learning_rate:
  value: 0.8226276980135283
num_heads:
  value: 4
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 3.3478734845226588
weight_phrase:
  value: 4.413903582099517
