wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 760
learning_rate:
  value: 0.5505338193758121
num_heads:
  value: 16
num_layers:
  value: 32
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 4.767654591083348
weight_phrase:
  value: 5.02892570686666
