wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 720
learning_rate:
  value: 0.8612743784303466
num_heads:
  value: 16
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 7.992081268296763
weight_phrase:
  value: 8.642065621475549
