wandb_version: 1

batch_size:
  value: 40
d_model:
  value: 1776
learning_rate:
  value: 0.7662212713783784
num_heads:
  value: 8
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 0.6379319256037885
weight_phrase:
  value: 4.824294647702672
