wandb_version: 1

batch_size:
  value: 64
d_model:
  value: 1888
learning_rate:
  value: 0.2183169880832847
num_heads:
  value: 4
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 6.092144985471651
weight_phrase:
  value: 3.3902114264498397
