wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 1752
learning_rate:
  value: 0.6750066776421095
num_heads:
  value: 4
num_layers:
  value: 32
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 9.208095272156283
weight_phrase:
  value: 8.13290987118823
