wandb_version: 1

batch_size:
  value: 32
d_model:
  value: 688
learning_rate:
  value: 0.5966565522587515
num_heads:
  value: 8
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 6.331229280015429
weight_phrase:
  value: 7.929083883519009
