wandb_version: 1

batch_size:
  value: 48
d_model:
  value: 1304
learning_rate:
  value: 0.15476297536809835
num_heads:
  value: 4
num_layers:
  value: 64
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 6.994976816675015
weight_phrase:
  value: 2.1518951368797854
