wandb_version: 1

d_model:
  value: 1760
learning_rate:
  value: 0.9124376356040492
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 1.854304565244348
weight_phrase:
  value: 7.271826536677597
