wandb_version: 1

d_model:
  value: 592
learning_rate:
  value: 0.4932509833071126
num_heads:
  value: 4
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 7.132385752781105
weight_phrase:
  value: 2.500296970832206
