wandb_version: 1

d_model:
  value: 1352
learning_rate:
  value: 0.997411651057676
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 9.85236008328655
weight_phrase:
  value: 6.0269187506434925
