wandb_version: 1

d_model:
  value: 1640
learning_rate:
  value: 0.34112905178539654
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 7.442343047180432
weight_phrase:
  value: 5.558965080252868
