wandb_version: 1

d_model:
  value: 712
learning_rate:
  value: 0.1127111248951318
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 6.82599331595036
weight_phrase:
  value: 7.641148662430688
