wandb_version: 1

d_model:
  value: 968
learning_rate:
  value: 0.6605166997944865
num_heads:
  value: 4
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 5.918956958133937
weight_phrase:
  value: 8.379425777389923
