wandb_version: 1

d_model:
  value: 1424
learning_rate:
  value: 0.5442833784089564
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 9.453989167892116
weight_phrase:
  value: 0.19775912869457457
