wandb_version: 1

d_model:
  value: 1008
learning_rate:
  value: 0.6030222394655816
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 4.297504494203182
weight_phrase:
  value: 2.403422166053816
