wandb_version: 1

d_model:
  value: 528
learning_rate:
  value: 0.5835092010055815
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 7.104708764529908
weight_phrase:
  value: 4.402527878073265
