wandb_version: 1

d_model:
  value: 976
learning_rate:
  value: 0.9006418642664629
num_heads:
  value: 4
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 7.210726229750661
weight_phrase:
  value: 0.961251694862454
