wandb_version: 1

d_model:
  value: 840
learning_rate:
  value: 0.21888105197596883
num_heads:
  value: 4
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 4.436261426123593
weight_phrase:
  value: 8.49547628408969
