wandb_version: 1

d_model:
  value: 1904
learning_rate:
  value: 0.8218000032482112
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 8.169098130063364
weight_phrase:
  value: 7.794411049392095
