wandb_version: 1

d_model:
  value: 1968
learning_rate:
  value: 0.04300667835894256
num_heads:
  value: 8
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 0.3568098017365662
weight_phrase:
  value: 0.11200525821717933
