wandb_version: 1

d_model:
  value: 784
learning_rate:
  value: 0.32102079965030794
num_heads:
  value: 4
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 2.8627891649584236
weight_phrase:
  value: 4.90063662033233
