wandb_version: 1

d_model:
  value: 1296
learning_rate:
  value: 0.8642538047103497
num_heads:
  value: 4
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 7.854444057486758
weight_phrase:
  value: 2.3749421153050365
