wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 960
learning_rate:
  value: 0.09645212230318022
num_heads:
  value: 16
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
