wandb_version: 1

batch_size:
  value: 48
d_model:
  value: 928
learning_rate:
  value: 0.046907536408612296
num_heads:
  value: 16
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
