wandb_version: 1

batch_size:
  value: 56
d_model:
  value: 1296
learning_rate:
  value: 0.024296484280146385
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
