wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1678142735.137674
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 37
      4: 3.7.13
      5: 0.13.5
      8:
      - 5
batch_size:
  desc: null
  value: 8
d_model:
  desc: null
  value: 1088
learning_rate:
  desc: null
  value: 0.7140309289546591
num_heads:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 32
optimizer:
  desc: null
  value: adam
tag_emb_dropout:
  desc: null
  value: 0.4
weight_activity:
  desc: null
  value: 4.7420648814348585
weight_phrase:
  desc: null
  value: 3.7253875873265807
