wandb_version: 1

d_model:
  value: 880
learning_rate:
  value: 0.5914833672286193
num_heads:
  value: 4
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 2.03576473365609
weight_phrase:
  value: 0.7355379770473525
