wandb_version: 1

d_model:
  value: 1544
learning_rate:
  value: 0.7995422461097469
num_heads:
  value: 4
num_layers:
  value: 4
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 8.114825832494743
weight_phrase:
  value: 8.244324721552667
