wandb_version: 1

d_model:
  value: 808
learning_rate:
  value: 0.4750842373024952
num_heads:
  value: 8
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 1.7725048037017688
weight_phrase:
  value: 3.092245978805035
