wandb_version: 1

batch_size:
  value: 56
d_model:
  value: 1496
learning_rate:
  value: 0.02162715460505349
num_heads:
  value: 16
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
