wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 512
learning_rate:
  value: 0.08800951770448863
num_heads:
  value: 8
num_layers:
  value: 32
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
