wandb_version: 1

d_model:
  value: 784
learning_rate:
  value: 0.3734785589799823
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 5.962657256130318
weight_phrase:
  value: 9.066603688964976
