wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1678159772.285473
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.13.5
      8:
      - 5
d_model:
  desc: null
  value: 1008
learning_rate:
  desc: null
  value: 0.6030222394655816
num_heads:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 16
optimizer:
  desc: null
  value: sgd
tag_emb_dropout:
  desc: null
  value: 0.3
weight_activity:
  desc: null
  value: 4.297504494203182
weight_phrase:
  desc: null
  value: 2.403422166053816
