wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 1216
learning_rate:
  value: 0.028090623858670206
num_heads:
  value: 16
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
