wandb_version: 1

batch_size:
  value: 32
d_model:
  value: 1096
learning_rate:
  value: 0.09246236069475566
num_heads:
  value: 16
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
