wandb_version: 1

batch_size:
  value: 64
d_model:
  value: 1368
learning_rate:
  value: 0.02745051917949941
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
