wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1416
learning_rate:
  value: 0.08137309988518789
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
