wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 1752
learning_rate:
  value: 0.05214969586644726
num_heads:
  value: 8
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
