wandb_version: 1

batch_size:
  value: 80
d_model:
  value: 648
learning_rate:
  value: 0.05045773964376733
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
