wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 960
learning_rate:
  value: 0.06439154814701217
num_heads:
  value: 4
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
