wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 792
learning_rate:
  value: 0.08918177135265526
num_heads:
  value: 8
num_layers:
  value: 32
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
