wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 1008
learning_rate:
  value: 0.01592104127272429
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
