wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 640
learning_rate:
  value: 0.09263232703977252
num_heads:
  value: 16
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
