wandb_version: 1

batch_size:
  value: 80
d_model:
  value: 584
learning_rate:
  value: 0.04947842411338624
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
