wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 872
learning_rate:
  value: 0.045774766456962906
num_heads:
  value: 4
num_layers:
  value: 4
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
