wandb_version: 1

d_model:
  value: 1160
learning_rate:
  value: 0.0387895534957744
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 0.07560257857584962
weight_phrase:
  value: 5.78382398959687
