wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 544
learning_rate:
  value: 0.0035474242241840927
num_heads:
  value: 16
num_layers:
  value: 4
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
