wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1678301283.535664
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.13.5
      8:
      - 5
optimizer:
  desc: null
  value: adam
weight_action:
  desc: null
  value: 2.0208996159443204
weight_activity:
  desc: null
  value: 5.805584514257797
weight_phrase:
  desc: null
  value: 8.31793316529905
