wandb_version: 1

d_model:
  value: 1328
learning_rate:
  value: 0.5750283808340864
num_heads:
  value: 8
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 5.044208327782385
weight_phrase:
  value: 7.687482934048181
