wandb_version: 1

d_model:
  value: 592
learning_rate:
  value: 0.8481726632840655
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 6.481949120078566
weight_phrase:
  value: 2.8770603565106634
