wandb_version: 1

d_model:
  value: 1000
learning_rate:
  value: 0.7363291854007029
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 9.721626910033244
weight_phrase:
  value: 1.5823710262829949
