wandb_version: 1

d_model:
  value: 1008
learning_rate:
  value: 0.44167930160594904
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 4.947319943358553
weight_phrase:
  value: 3.9879540912748688
