wandb_version: 1

d_model:
  value: 1256
learning_rate:
  value: 0.5443964119931051
num_heads:
  value: 4
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 4.9871033236670925
weight_phrase:
  value: 9.055003522362409
