wandb_version: 1

d_model:
  value: 1480
learning_rate:
  value: 0.42206057205780045
num_heads:
  value: 8
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
weight_activity:
  value: 9.090024088576204
weight_phrase:
  value: 5.239766250398658
