wandb_version: 1

d_model:
  value: 1544
learning_rate:
  value: 0.5805265120250174
num_heads:
  value: 8
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 4.86470389523498
weight_phrase:
  value: 2.911387764048212
