wandb_version: 1

d_model:
  value: 520
learning_rate:
  value: 0.14299654938816295
num_heads:
  value: 4
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 1.710748699407827
weight_phrase:
  value: 0.6198460892059587
