wandb_version: 1

d_model:
  value: 1864
learning_rate:
  value: 0.6338444193662963
num_heads:
  value: 8
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
weight_activity:
  value: 1.5861836349080594
weight_phrase:
  value: 5.783741530744405
