wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1678300967.469137
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.13
      5: 0.13.5
      8:
      - 5
optimizer:
  desc: null
  value: adam
weight_action:
  desc: null
  value: 5.375333517151413
weight_activity:
  desc: null
  value: 1.303968914243674
weight_phrase:
  desc: null
  value: 2.9127286151833784
