wandb_version: 1

batch_size:
  value: 16
d_model:
  value: 560
learning_rate:
  value: 0.05114909831375092
num_heads:
  value: 4
num_layers:
  value: 4
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.4
