wandb_version: 1

batch_size:
  value: 32
d_model:
  value: 1280
learning_rate:
  value: 0.06794695606823646
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.3
