wandb_version: 1

batch_size:
  value: 24
d_model:
  value: 768
learning_rate:
  value: 0.0651586844520404
num_heads:
  value: 8
num_layers:
  value: 8
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
