wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1088
learning_rate:
  value: 0.7140309289546591
num_heads:
  value: 8
num_layers:
  value: 32
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.4
weight_activity:
  value: 4.7420648814348585
weight_phrase:
  value: 3.7253875873265807
