wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 592
learning_rate:
  value: 0.02230322159186392
num_heads:
  value: 8
num_layers:
  value: 8
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
