wandb_version: 1

batch_size:
  value: 72
d_model:
  value: 1272
learning_rate:
  value: 0.06671558836607465
num_heads:
  value: 8
num_layers:
  value: 64
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
