wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 808
learning_rate:
  value: 0.055162195144715986
num_heads:
  value: 4
num_layers:
  value: 2
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
