wandb_version: 1

batch_size:
  value: 72
d_model:
  value: 528
learning_rate:
  value: 0.005261132558499183
num_heads:
  value: 4
num_layers:
  value: 64
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.2
