wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1384
learning_rate:
  value: 0.03045389603122527
num_heads:
  value: 16
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
