wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 1704
learning_rate:
  value: 0.028302930781853544
num_heads:
  value: 8
num_layers:
  value: 16
optimizer:
  value: sgd
tag_emb_dropout:
  value: 0.2
