wandb_version: 1

batch_size:
  value: 40
d_model:
  value: 1144
learning_rate:
  value: 0.09923994405265932
num_heads:
  value: 8
num_layers:
  value: 2
optimizer:
  value: adam
tag_emb_dropout:
  value: 0.3
